### ISSUE TITLE
Pandastream change datetime format

### ISSUE THREAD

**Issue by mrloop** [maxhille/panda-lib#3]
Pandastream have changed the datetime format for videos from "yyyy/MM/dd HH:mm:ss Z" to "yyyy-MM-dd'T'HH:mm:ss.SSSX" (you'll need Java 7 or greater to use this format). I've contacted them requesting more information on this change whither it is intentional or not. If intentional will submit pull request, no point doing so now as I suspect this API was unintended, it breaks their own ruby client.
Currently posting local files to pandastream works but the json that is returned isn't parsed and panda lib throws a com.google.gson.JsonSyntaxException

**Comment by mrloop** [comment]
Filed similar issue for panda ruby gem, https://github.com/pandastream/panda_gem/issues/16

**Comment by zimbatm** [comment]
Thanks, this is a bug in our API. I'm going to deploy a revert today and add some unit tests to make sure it doesn't happen again.

**Comment by mrloop** [comment]
Thanks @zimbatm. Running tests and panda-lib is passing again.
